export default {
  token: null,
  errorMessage: '',
  emailError: '',
  passwordError: '',
  email: '',
  password: '',
  isLoading: false,
  language: 'en',
  JWTToken: null,
  refreshToken: null,
  firebaseUser: null,
  user: null,
  profileComplete: false,
  profileIsComplete: '',
  profile: {
    firstName: '',
    lastName: '',
    userId: '',
    gender: '',
    imageUrl: '',
    profileUrl: '',
    dob: '',
    interests: '',
    whyBecomeMentor: '',
    expertise: '',
    company: '',
    jobTitle: '',
    bio: '',
  },
  userLogin: false,
  scheduleStartTime: {
    hour: 0,
    day: 0,
    week: 0,
  },
};
